lab3: main.o
		g++ -g -std=c++11 -Wall main.o -o lab3

main.o: main.cpp LinkedList.h LinkedList.hpp Node.h Node.hpp MedicalExecutive.h MedicalExecutive.hpp City.h City.hpp
		g++ -g -std=c++11 -Wall -c main.cpp

clean:
		rm *.o lab3
